package fr.christophetd.log4shell.vulnerableapp.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import fr.christophetd.log4shell.vulnerableapp.entities.User;
import fr.christophetd.log4shell.vulnerableapp.repositories.UserRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path="/user") // This means URL's start with /usr (after Application path)
public class UserController {

@Autowired // This means to get the bean called userRepository
// Which is auto-generated by Spring, we will use it to handle the data
private UserRepository userRepository;

@PostMapping(path="/add") // Map ONLY POST Requests
public @ResponseBody String addNewUser (@RequestParam String name
 , @RequestParam String email, String ccNum, String ccExpiration, Integer ccSecCode, Integer ccZipCode) {
// @ResponseBody means the returned String is the response, not a view name
// @RequestParam means it is a parameter from the GET or POST request

    User user = new User();
    user.setName(name);
    user.setEmail(email);
    user.setCCNum(ccNum);
    user.setCCExpiration(ccExpiration);
    user.setCCSecCode(ccSecCode);
    user.setCCZipCode(ccZipCode);
    userRepository.save(user);
    return "Saved";
}

@GetMapping(path="/all")
public @ResponseBody Iterable<User> getAllUsers() {
// This returns a JSON or XML with the users
    return userRepository.findAll();
}

}
